name: "Nightly deploy"

on:
  workflow_dispatch:

jobs:
  nightly:
    name: Deploy nightly
    strategy:
      fail-fast: false
      matrix:
        refs: [main]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.refs }}
          submodules: 'recursive'
      - name: Patch versions
        run: |
          sed -i 's/^#define[[:space:]]\+PICO_FIDO_VERSION[[:space:]]\+0x0606/#define PICO_FIDO_VERSION 0x0702/' \
            pico-fido/src/fido/version.h

          sed -i 's/^#define[[:space:]]\+PICO_KEYS_SDK_VERSION[[:space:]]\+0x0700/#define PICO_KEYS_SDK_VERSION 0x0802/' \
            pico-keys-sdk/src/pico_keys_version.h
          grep -q '0x0702' pico-fido/src/fido/version.h || exit 1
          grep -q '0x0802' pico-keys-sdk/src/pico_keys_version.h || exit 1

      - name: Restore private key
        run: |
          echo "${{ secrets.PRIVATE_KEY_B64 }}" | base64 -d > private.pem
          chmod 600 private.pem
      - name : Build
        env:
          PICO_SDK_PATH: ../pico-sdk
          SECURE_BOOT_PKEY: ../private.pem
        run: |
           ./workflows/autobuild.sh pico
           ./build_pico_fido2.sh
      - name: Delete private key
        run: rm private.pem
      - name: Update nightly release
        uses: pyTooling/Actions/releaser@v6.7.0
        with:
          tag: nightly-${{ matrix.refs }}
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: release/*.*
